### ISSUE TITLE
organisationsnummer

### ISSUE THREAD

**Issue by jonasbring** [c7/personnummer#5]
Hi, Would it be possible to add checks for valid organisationsnummer (month > 20) as well?

**Comment by buren** [comment]
The link to the PDF has changed.. its now ([PDF, in Swedish](https://www.skatteverket.se/download/18.70ac421612e2a997f85800040284/1359707510840/70909.pdf)).

**Comment by vasilakisfil** [comment]
@buren it doesn't work either

**Comment by buren** [comment]
@vasilakisfil true, seems like Skatteverket replaces the link every now and then.. I update the link to point to the Internet Archives version.. ([PDF, in Swedish (Internet Archive)](https://web.archive.org/web/20151211071212/http://www.skatteverket.se/download/18.70ac421612e2a997f85800040284/1359707510840/70909.pdf))
